# Site settings
title: TinySat
description: "Solar Powered Blinken Lights based on ATtiny13A"
show_downloads: true
author:
  name: wagiminator
  email: wagiminator@web.de
minima:
  social_links:
    github: wagiminator
    youtube: wagiminator
#description: "Great site about Jekyll on GH-Pages."

# Build settings
#theme: minima
#remote_theme: jekyll/minima
#remote_theme: alshedivat/al-folio 

theme: jekyll-theme-minimal
