theme: jekyll-theme-architect
title: TinySat
description: "Solar Powered Blinken Lights based on ATtiny13A"
show_downloads: true
github:
  zip_url: https://github.com/wagiminator/ATtiny13-TinySat/zipball/main
  tar_url: https://github.com/wagiminator/ATtiny13-TinySat/tarball/main
